### ISSUE TITLE
ReactNative Style

### ISSUE THREAD

**Issue by KatuGT** [JavGt/vscode-component-creator#2]
Hola, vengo usando tu extensión hace un tiempo, ahora estoy trabajando con react native y me gustaría tener esta opción aquí , no es muy diferente a los que ya tenes, por ahí solo tendrías que agregar un archivo de estilos con la siguiente linea

`export const styles = StyleSheet.create({})`

y el archivo del componente algo así
```
import { Text } from 'react-native'
import { styles } from './Historial.styles';

const Historial = () => {
	return <Text>Historial</Text>;
};

export default Historial;
```

**Comment by JavGt** [comment]
Una disculpa por la demora, se ha trabajado en la implementación que propusiste y esta ha sido la respuesta, actualmente hay una propiedad llamada `reactCreateComponent.settings.native.styleShee` en tu configuración,

> Esta propiedad no fue agregada en los quick pick para no saturar de opciones

<img width="517" alt="image" src="https://github.com/JavGt/vscode-component-creator/assets/82567321/11c30f75-7ea0-42a0-a433-e22cb121bc5b">

Su default es `true`, significa que siempre te creara en tu componente el clásico:
```Js
const styles = StyleSheet.create({
//...
});
```

Para tu caso en específico, seria `file`, lo cual creara un fichero en la misma ruta de tu componente.

> Puedes leer más sobre esa y más propiedades y la [documentacion](https://github.com/JavGt/vscode-component-creator/blob/main/docs/settings.md)

Espero esta implementación te sea de mucha utilidad y gracias por el apoyo y de nuevo, una disculpa por la demora.
